FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM alpine:latest AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist

CMD ["sh", "-c", "cp -rf /app/dist/. /app/volume/ && sleep infinity"]